"""add description to table blogs

Revision ID: 5cdacaf0024e
Revises: 230dece3c842
Create Date: 2024-06-04 23:53:47.903898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdacaf0024e'
down_revision: Union[str, None] = '230dece3c842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'description')
    # ### end Alembic commands ###
