"""add category  to table blogs

Revision ID: ee5bdf57bfbc
Revises: 5cdacaf0024e
Create Date: 2024-06-05 00:07:47.727927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5bdf57bfbc'
down_revision: Union[str, None] = '5cdacaf0024e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###
